/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as SkillsDatabaseIdRouteImport } from './routes/skills.$databaseId'

const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsDatabaseIdRoute = SkillsDatabaseIdRouteImport.update({
  id: '/skills/$databaseId',
  path: '/skills/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/favicon.ico': typeof FaviconDoticoRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
}
export interface FileRoutesByTo {
  '/favicon.ico': typeof FaviconDoticoRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/favicon.ico': typeof FaviconDoticoRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/favicon.ico' | '/skills/$databaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/favicon.ico' | '/skills/$databaseId'
  id: '__root__' | '/favicon.ico' | '/skills/$databaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  SkillsDatabaseIdRoute: typeof SkillsDatabaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$databaseId': {
      id: '/skills/$databaseId'
      path: '/skills/$databaseId'
      fullPath: '/skills/$databaseId'
      preLoaderRoute: typeof SkillsDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FaviconDoticoRoute: FaviconDoticoRoute,
  SkillsDatabaseIdRoute: SkillsDatabaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
