import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/credits/page.tsx", import.meta.url), "utf8");
const client = readFileSync(new URL("../app/credits/credits-client.tsx", import.meta.url), "utf8");
const wallet = readFileSync(new URL("../lib/credits-wallet.ts", import.meta.url), "utf8");
const url = readFileSync(new URL("../lib/credits-url.ts", import.meta.url), "utf8");
const idl = readFileSync(new URL("../lib/vfs-idl.ts", import.meta.url), "utf8");
const vfsClient = readFileSync(new URL("../lib/vfs-client.ts", import.meta.url), "utf8");
const connectOisy = sliceBetween(wallet, "export async function connectOisyWallet", "export async function connectPlugWallet");
const connectPlug = sliceBetween(wallet, "export async function connectPlugWallet", "export async function purchaseCreditsWithOisy");
const purchaseOisy = sliceBetween(wallet, "export async function purchaseCreditsWithOisy", "export async function purchaseCreditsWithPlug");
const purchasePlug = sliceBetween(wallet, "export async function purchaseCreditsWithPlug", "function approveParams");

assert.match(page, /\/credits/);
assert.doesNotMatch(page, /canister_id \?\? params\.canisterId/);
assert.doesNotMatch(page, /amount_e8s \?\? params\.amountE8s/);
assert.match(client, /purchaseCreditsWithOisy/);
assert.match(client, /purchaseCreditsWithPlug/);
assert.match(client, /connectOisyWallet/);
assert.match(client, /connectPlugWallet/);
assert.match(client, /Connect OISY/);
assert.match(client, /Connect Plug/);
assert.match(client, /Purchase credits with OISY/);
assert.match(client, /Purchase credits with Plug/);
assert.match(client, /const purchaseDisabled = !selectedProvider \|\| Boolean\(error\) \|\| Boolean\(amountError\) \|\| busy/);
assert.match(client, /function WalletConnect/);
assert.match(client, /onClick=\{\(\) => void purchase\(\)\}/);
assert.doesNotMatch(client, /onCredits/);
assert.match(client, /parseCreditsAmountInput/);
assert.match(client, /parseCreditsTarget/);
assert.match(client, /KINIC/);
assert.match(wallet, /export async function connectOisyWallet/);
assert.match(wallet, /export async function connectPlugWallet/);
assert.match(wallet, /export async function purchaseCreditsWithOisy\(request: CreditsPurchaseRequest, connection: ConnectedOisyWallet\)/);
assert.match(wallet, /export async function purchaseCreditsWithPlug\(request: CreditsPurchaseRequest, connection: ConnectedPlugWallet\)/);
assert.match(connectOisy, /IcrcWallet\.connect/);
assert.match(connectOisy, /wallet\.accounts\(\)/);
assert.doesNotMatch(connectOisy, /getCreditsConfig|previewDatabaseCreditPurchase|whitelist/);
assert.match(connectPlug, /plug\.requestConnect\(\{\s*host:/);
assert.doesNotMatch(connectPlug, /getCreditsConfig|previewDatabaseCreditPurchase|whitelist/);
assert.match(purchaseOisy, /getCreditsConfig\(request\.canisterId\)/);
assert.match(purchaseOisy, /previewDatabaseCreditPurchase\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(purchasePlug, /getCreditsConfig\(request\.canisterId\)/);
assert.match(purchasePlug, /previewDatabaseCreditPurchase\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(purchasePlug, /whitelist: \[request\.canisterId, config\.kinicLedgerCanisterId\]/);
assert.match(wallet, /icrc2_approve/);
assert.match(wallet, /icrc2_allowance/);
assert.match(wallet, /icrc1_fee/);
assert.match(wallet, /icrc1_fee: idl\.Func\(\[\], \[idl\.Nat\], \["query"\]\)/);
assert.match(wallet, /icrc2_allowance: idl\.Func\(\[allowanceArgs\], \[allowance\], \["query"\]\)/);
assert.match(wallet, /icrc2_approve: idl\.Func\(\[approveArgs\], \[idl\.Variant\(\{ Ok: idl\.Nat, Err: approveError \}\)\], \[\]\)/);
assert.match(wallet, /purchase_database_credits/);
assert.match(wallet, /previewDatabaseCreditPurchase\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(wallet, /function allowanceForCreditPurchase\(amountE8s: bigint, transferFeeE8s: bigint\)/);
assert.match(wallet, /return amountE8s \+ transferFeeE8s/);
assert.match(wallet, /approveParams\(request\.canisterId, approvedAllowanceE8s, currentAllowance, expiresAt\)/);
assert.match(wallet, /rawApproveArgs\(request\.canisterId, approvedAllowanceE8s, currentAllowance\.allowance, expiresAt\)/);
assert.match(wallet, /expected_allowance: \[expectedAllowanceE8s\]/);
assert.match(wallet, /expires_at: \[expiresAt\]/);
assert.match(wallet, /APPROVE_EXPIRES_IN_MS = 30 \* 60 \* 1000/);
assert.match(wallet, /assertConfiguredCreditsCanister\(request\.canisterId\)/);
assert.match(wallet, /purchase_database_credits\(request\.databaseId, request\.amountE8s\)/);
assert.match(wallet, /spender: \{ owner: Principal\.fromText\(canisterId\), subaccount: \[\] \}/);
assert.match(wallet, /DEFAULT_OISY_SIGNER_URL/);
assert.match(wallet, /credits purchase failed after approve; approval remains until/);
assert.match(client, /purchased credits/);
assert.match(client, /creditedAmountE8s/);
assert.match(client, /approved allowance/);
assert.doesNotMatch(client, /Wallet approval uses the DB credit amount plus the ledger transfer fee/);
assert.match(client, /transfer fee/);
assert.match(client, /Any authenticated wallet can purchase non-refundable credits/);
assert.doesNotMatch(client, /withdraw KINIC|database balance/);
assert.doesNotMatch(client, /credits canister does not match NEXT_PUBLIC_KINIC_WIKI_CANISTER_ID/);
assert.match(url, /KINIC amount must be a decimal with up to 8 fractional digits/);
assert.match(url, /KINIC amount must be <= u64::MAX/);
assert.match(url, /database_id is required/);
assert.doesNotMatch(url, /params\.set\("amount_e8s"/);
assert.match(idl, /get_credits_config/);
assert.match(idl, /preview_database_credit_purchase/);
assert.match(idl, /purchase_database_credits/);
assert.match(vfsClient, /export async function getCreditsConfig/);
assert.match(vfsClient, /export async function previewDatabaseCreditPurchase/);

console.log("Credits checks OK");

function sliceBetween(source, startText, endText) {
  const start = source.indexOf(startText);
  assert.notEqual(start, -1, `${startText} not found`);
  const end = source.indexOf(endText, start + startText.length);
  assert.notEqual(end, -1, `${endText} not found`);
  return source.slice(start, end);
}
