import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/deposit/page.tsx", import.meta.url), "utf8");
const client = readFileSync(new URL("../app/deposit/deposit-client.tsx", import.meta.url), "utf8");
const wallet = readFileSync(new URL("../lib/deposit-wallet.ts", import.meta.url), "utf8");
const url = readFileSync(new URL("../lib/deposit-url.ts", import.meta.url), "utf8");
const idl = readFileSync(new URL("../lib/vfs-idl.ts", import.meta.url), "utf8");
const vfsClient = readFileSync(new URL("../lib/vfs-client.ts", import.meta.url), "utf8");
const connectOisy = sliceBetween(wallet, "export async function connectOisyWallet", "export async function connectPlugWallet");
const connectPlug = sliceBetween(wallet, "export async function connectPlugWallet", "export async function depositWithOisy");
const depositOisy = sliceBetween(wallet, "export async function depositWithOisy", "export async function depositWithPlug");
const depositPlug = sliceBetween(wallet, "export async function depositWithPlug", "function approveParams");

assert.match(page, /\/deposit/);
assert.doesNotMatch(page, /canister_id \?\? params\.canisterId/);
assert.doesNotMatch(page, /amount_e8s \?\? params\.amountE8s/);
assert.match(client, /depositWithOisy/);
assert.match(client, /depositWithPlug/);
assert.match(client, /connectOisyWallet/);
assert.match(client, /connectPlugWallet/);
assert.match(client, /Connect OISY/);
assert.match(client, /Connect Plug/);
assert.match(client, /Deposit with OISY/);
assert.match(client, /Deposit with Plug/);
assert.match(client, /const depositDisabled = !selectedProvider \|\| Boolean\(error\) \|\| Boolean\(amountError\) \|\| busy/);
assert.match(client, /function WalletConnect/);
assert.match(client, /onClick=\{\(\) => void deposit\(\)\}/);
assert.doesNotMatch(client, /onDeposit/);
assert.match(client, /parseDepositAmountInput/);
assert.match(client, /parseDepositTarget/);
assert.match(client, /KINIC/);
assert.match(wallet, /export async function connectOisyWallet/);
assert.match(wallet, /export async function connectPlugWallet/);
assert.match(wallet, /export async function depositWithOisy\(request: DepositRequest, connection: ConnectedOisyWallet\)/);
assert.match(wallet, /export async function depositWithPlug\(request: DepositRequest, connection: ConnectedPlugWallet\)/);
assert.match(connectOisy, /IcrcWallet\.connect/);
assert.match(connectOisy, /wallet\.accounts\(\)/);
assert.doesNotMatch(connectOisy, /getBillingConfig|previewDatabaseTopUp|whitelist/);
assert.match(connectPlug, /plug\.requestConnect\(\{\s*host:/);
assert.doesNotMatch(connectPlug, /getBillingConfig|previewDatabaseTopUp|whitelist/);
assert.match(depositOisy, /getBillingConfig\(request\.canisterId\)/);
assert.match(depositOisy, /previewDatabaseTopUp\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(depositPlug, /getBillingConfig\(request\.canisterId\)/);
assert.match(depositPlug, /previewDatabaseTopUp\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(depositPlug, /whitelist: \[request\.canisterId, config\.kinicLedgerCanisterId\]/);
assert.match(wallet, /icrc2_approve/);
assert.match(wallet, /icrc2_allowance/);
assert.match(wallet, /icrc1_fee/);
assert.match(wallet, /icrc1_fee: idl\.Func\(\[\], \[idl\.Nat\], \["query"\]\)/);
assert.match(wallet, /icrc2_allowance: idl\.Func\(\[allowanceArgs\], \[allowance\], \["query"\]\)/);
assert.match(wallet, /icrc2_approve: idl\.Func\(\[approveArgs\], \[idl\.Variant\(\{ Ok: idl\.Nat, Err: approveError \}\)\], \[\]\)/);
assert.match(wallet, /top_up_database/);
assert.match(wallet, /previewDatabaseTopUp\(request\.canisterId, request\.databaseId, request\.amountE8s\)/);
assert.match(wallet, /function allowanceForTopUp\(amountE8s: bigint, transferFeeE8s: bigint\)/);
assert.match(wallet, /return amountE8s \+ transferFeeE8s/);
assert.match(wallet, /approveParams\(request\.canisterId, approvedAllowanceE8s, currentAllowance, expiresAt\)/);
assert.match(wallet, /rawApproveArgs\(request\.canisterId, approvedAllowanceE8s, currentAllowance\.allowance, expiresAt\)/);
assert.match(wallet, /expected_allowance: \[expectedAllowanceE8s\]/);
assert.match(wallet, /expires_at: \[expiresAt\]/);
assert.match(wallet, /APPROVE_EXPIRES_IN_MS = 30 \* 60 \* 1000/);
assert.match(wallet, /assertConfiguredDepositCanister\(request\.canisterId\)/);
assert.match(wallet, /top_up_database\(request\.databaseId, request\.amountE8s\)/);
assert.match(wallet, /spender: \{ owner: Principal\.fromText\(canisterId\), subaccount: \[\] \}/);
assert.match(wallet, /DEFAULT_OISY_SIGNER_URL/);
assert.match(wallet, /top-up failed after approve; approval remains until/);
assert.match(client, /DB credited/);
assert.match(client, /DB credited amount/);
assert.match(client, /approved allowance/);
assert.doesNotMatch(client, /Wallet approval uses the DB credit amount plus the ledger transfer fee/);
assert.match(client, /transfer fee/);
assert.match(client, /Any authenticated wallet can fund this database/);
assert.match(client, /Only database owners can withdraw KINIC from the database balance/);
assert.doesNotMatch(client, /deposit canister does not match NEXT_PUBLIC_KINIC_WIKI_CANISTER_ID/);
assert.match(url, /KINIC amount must be a decimal with up to 8 fractional digits/);
assert.match(url, /KINIC amount must be <= u64::MAX/);
assert.match(url, /database_id is required/);
assert.doesNotMatch(url, /params\.set\("amount_e8s"/);
assert.match(idl, /get_billing_config/);
assert.match(idl, /preview_database_top_up/);
assert.match(idl, /top_up_database/);
assert.match(vfsClient, /export async function getBillingConfig/);
assert.match(vfsClient, /export async function previewDatabaseTopUp/);

console.log("Deposit checks OK");

function sliceBetween(source, startText, endText) {
  const start = source.indexOf(startText);
  assert.notEqual(start, -1, `${startText} not found`);
  const end = source.indexOf(endText, start + startText.length);
  assert.notEqual(end, -1, `${endText} not found`);
  return source.slice(start, end);
}
