/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.nns.jsonc --include-runtime=false --env-interface=NnsWorkerBindings src/nns-worker-configuration.d.ts` (hash: b81861cbab99014a06438f7134178721)
interface __BaseEnv_NnsWorkerBindings {
	DB: D1Database;
	NNS_PROPOSAL_REVIEW_QUEUE: Queue;
	NNS_PROPOSAL_REVIEW_DLQ: Queue;
	KINIC_WIKI_CANISTER_ID: "6emaw-iyaaa-aaaay-aacka-cai";
	KINIC_WIKI_IC_HOST: "https://icp0.io";
	KINIC_NNS_API_BASE_URL: "https://ic-api.internetcomputer.org/api/v3";
	KINIC_NNS_REVIEW_MODEL: "deepseek-v4-flash";
	KINIC_NNS_MAX_RAW_CHARS: "120000";
	KINIC_NNS_MAX_FETCHED_BYTES: "5000000";
	KINIC_NNS_MAX_SOURCE_CHARS: "300000";
	KINIC_NNS_MAX_OUTPUT_TOKENS: "6000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./nns-index");
	}
	interface Env extends __BaseEnv_NnsWorkerBindings {}
}
interface NnsWorkerBindings extends __BaseEnv_NnsWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KINIC_WIKI_CANISTER_ID" | "KINIC_WIKI_IC_HOST" | "KINIC_NNS_API_BASE_URL" | "KINIC_NNS_REVIEW_MODEL" | "KINIC_NNS_MAX_RAW_CHARS" | "KINIC_NNS_MAX_FETCHED_BYTES" | "KINIC_NNS_MAX_SOURCE_CHARS" | "KINIC_NNS_MAX_OUTPUT_TOKENS">> {}
}
