/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.nns-voter.jsonc --include-runtime=false --env-interface=NnsVoterBindings src/nns-voter-configuration.d.ts` (hash: 8d8a4daac4c91e77504c34ebd6f73dd3)
interface __BaseEnv_NnsVoterBindings {
	NNS_VOTE_DLQ: Queue;
	NNS_PROPOSAL_REVIEW_QUEUE: Queue;
	KINIC_NNS_AUTOVOTE_ENABLED: "false";
	KINIC_WIKI_CANISTER_ID: "6emaw-iyaaa-aaaay-aacka-cai";
	KINIC_WIKI_IC_HOST: "https://icp0.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./nns-voter");
	}
	interface Env extends __BaseEnv_NnsVoterBindings {}
}
interface NnsVoterBindings extends __BaseEnv_NnsVoterBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KINIC_NNS_AUTOVOTE_ENABLED" | "KINIC_WIKI_CANISTER_ID" | "KINIC_WIKI_IC_HOST">> {}
}
