// Where: workers/wiki-generator/src/render.ts
// What: Markdown rendering and target path safety helpers.
// Why: LLM JSON must become a stable generated page before VFS writes.
import { SCHEMA_VERSION, type SearchNodeHit, type WikiDraft, type WikiDraftItem, type WikiNode } from "./types.js";

export function slugForGeneratedPage(generated: WikiDraft, fallbackBase: string): string {
  const slug = filenameSegment(generated.slug) || filenameSegment(generated.title) || filenameSegment(fallbackBase);
  if (!slug) {
    throw new Error("generated page needs a usable title or slug");
  }
  return slug;
}

export function renderGeneratedMarkdown(draft: WikiDraft, source: WikiNode, contextHits: SearchNodeHit[]): string {
  const labels = draft.labels;
  return [
    `# ${draft.title}`,
    "",
    `- Source: [${source.path}](${source.path})`,
    `- Generated by: wiki-generator v${SCHEMA_VERSION}`,
    "",
    `## ${labels.summary}`,
    "",
    draft.summary,
    "",
    renderItems(labels.key_facts, draft.key_facts, labels.none),
    renderItems(labels.decisions, draft.decisions, labels.none),
    renderItems(labels.open_questions, draft.open_questions, labels.none),
    renderItems(labels.follow_ups, draft.follow_ups, labels.none),
    renderContext(contextHits, labels.related_context),
    `## ${labels.provenance}`,
    "",
    `- source_path: ${source.path}`,
    `- source_etag: ${source.etag}`
  ]
    .filter((part) => part !== "")
    .join("\n");
}

export function ensureTargetCanBeWritten(existingContent: string | null, targetPath: string, sourcePath: string): void {
  if (existingContent !== null && !existingContent.includes(sourcePath)) {
    throw new Error(`target exists without matching provenance: ${targetPath}`);
  }
}

function filenameSegment(value: string): string {
  const candidate = value
    .trim()
    .replace(/\.md$/i, "")
    .trim()
    .toLowerCase()
    .replace(/[\\/\u0000-\u001f\u007f]+/g, "-")
    .replace(/\s+/g, "-")
    .replace(/[!"#$%&'()*+,/:;<=>?@[\]^`{|}~]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  const truncated = Array.from(candidate).slice(0, 80).join("").replace(/^-+|-+$/g, "");
  if (truncated === "." || truncated === "..") return "";
  return truncated;
}

function renderItems(title: string, items: WikiDraftItem[], noneLabel: string): string {
  if (items.length === 0) {
    return `## ${title}\n\n- ${noneLabel}\n`;
  }
  return `## ${title}\n\n${items.map((item) => `- ${item.text} ([source](${item.source_path}))`).join("\n")}\n`;
}

function renderContext(contextHits: SearchNodeHit[], title: string): string {
  if (contextHits.length === 0) return "";
  return `## ${title}\n\n${contextHits.map((hit) => `- [${hit.path}](${hit.path})`).join("\n")}\n`;
}
