/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 26b42ee3ce5623ba85f6fb7b626313ef)
interface __BaseEnv_Env {
	LINK_PREVIEW_IMAGES: R2Bucket;
	DB: D1Database;
	WIKI_GENERATION_QUEUE: Queue;
	WIKI_GENERATION_DLQ: Queue;
	KINIC_WIKI_CANISTER_ID: "6emaw-iyaaa-aaaay-aacka-cai";
	KINIC_WIKI_IC_HOST: "https://icp0.io";
	KINIC_WIKI_WORKER_MODEL: "deepseek-v4-flash";
	KINIC_WIKI_WORKER_TARGET_ROOT: "/Knowledge/conversations";
	KINIC_WIKI_WORKER_SOURCE_PREFIX: "/Sources";
	KINIC_WIKI_WORKER_CONTEXT_PREFIX: "/";
	NNS_PROPOSAL_REVIEW_SERVICE: Fetcher /* kinic-nns-proposal-review */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KINIC_WIKI_CANISTER_ID" | "KINIC_WIKI_IC_HOST" | "KINIC_WIKI_WORKER_MODEL" | "KINIC_WIKI_WORKER_TARGET_ROOT" | "KINIC_WIKI_WORKER_SOURCE_PREFIX" | "KINIC_WIKI_WORKER_CONTEXT_PREFIX">> {}
}
