// Non-secret bindings are generated by `pnpm cf-typegen` from cloudflare.config.ts.
export type Env = AssistantEnv & {
  OPENAI_API_KEY?: string;
  DEEPSEEK_API_KEY?: string;
  TYPESAFE_API_KEY?: string;
  ASSISTANT_KEY_ENCRYPTION_KEY?: string;
};
