import Foundation

/// Pins a research conversation to the account, database and task revision that requested it.
struct WorkItemResearchContext: Codable, Equatable, Sendable {
    let principal: String
    let databaseId: String
    let itemId: String
    let itemEtag: String

    func belongsTo(principal: String, databaseId: String, itemId: String) -> Bool {
        self.principal == principal && self.databaseId == databaseId && self.itemId == itemId
    }
}

enum WorkItemResearch {
    static func prompt(for item: WorkItem) -> String {
        var parts = [
            "Research the following work item using this Wiki database. Return a useful result with cited evidence, distinguish missing information from verified findings, and suggest the next action. Do not claim to have completed any external action.",
            "Work item: " + item.title,
            item.body
        ]
        if let path = item.source?.path { parts.append("Source Wiki path: " + path) }
        if let url = item.source?.url { parts.append("Source URL (reference only): " + url) }
        return parts.filter { !$0.isEmpty }.joined(separator: "\n\n")
    }

    static func isFinished(_ message: AskAIMessage) -> Bool {
        message.role == .assistant && [.complete, .insufficient].contains(message.state)
            && !message.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    /// Deterministic content and comment ID let retries reconcile a lost write acknowledgement.
    static func comment(question: String, answer: AskAIMessage, databaseId: String) -> String {
        var parts = ["## AI research result", "Generated by Ask AI. Review before marking this work item complete.",
                     "### Request\n" + quote(question), "### Result\n" + answer.text]
        if answer.state == .insufficient {
            parts.append("Evidence is insufficient. The references below are possible sources, not a verified answer.")
        } else if answer.sources.isEmpty {
            parts.append("This result has no verified Wiki citations.")
        }
        if !answer.sources.isEmpty {
            parts.append(answer.state == .insufficient ? "### Possible sources" : "### Sources")
            for source in answer.sources {
                var allowed = CharacterSet.urlPathAllowed
                allowed.remove(charactersIn: "?#()[]\\")
                let path = ("/db/" + databaseId + source.path).addingPercentEncoding(withAllowedCharacters: allowed) ?? ""
                parts.append("#### " + source.id + "\n\n" + quote(source.path) + "\n\n" + quote(source.excerpt) + "\n\n[Open source](https://wiki.kinic.xyz" + path + ")")
            }
        }
        return parts.joined(separator: "\n\n")
    }

    private static func quote(_ text: String) -> String {
        text.components(separatedBy: "\n").map { "> " + $0 }.joined(separator: "\n")
    }
}
