// Generated by scripts/generate-vfs-idl.mjs from crates/vfs_canister/vfs.did.
// Do not edit by hand.
import { Actor } from "@icp-sdk/core/agent";
import { IDL } from "@icp-sdk/core/candid";

type ActorInterfaceFactory = Parameters<typeof Actor.createActor>[0];

export const idlFactory: ActorInterfaceFactory = ({ IDL: idl }) => {
  const CanisterHealth = idl.Record({ cycles_balance: idl.Nat });
  const DatabaseRole = idl.Variant({ Reader: idl.Null, Writer: idl.Null, Owner: idl.Null });
  const DatabaseStatus = idl.Variant({
    Active: idl.Null,
    Pending: idl.Null,
    Restoring: idl.Null,
    Archiving: idl.Null,
    Archived: idl.Null,
    Deleted: idl.Null
  });
  const DatabaseSummary = idl.Record({
    status: DatabaseStatus,
    role: DatabaseRole,
    logical_size_bytes: idl.Nat64,
    database_id: idl.Text,
    name: idl.Text,
    cycles_balance: idl.Opt(idl.Nat64),
    cycles_suspended_at_ms: idl.Opt(idl.Int64),
    archived_at_ms: idl.Opt(idl.Int64),
    deleted_at_ms: idl.Opt(idl.Int64)
  });
  const CyclesTopUpConfig = idl.Record({ enabled: idl.Bool, threshold_cycles: idl.Nat, launcher_principal: idl.Text });
  const CyclesBillingConfig = idl.Record({
    cycles_per_kinic: idl.Nat64,
    min_update_cycles: idl.Nat64,
    top_up: CyclesTopUpConfig,
    kinic_ledger_canister_id: idl.Text,
    billing_authority_id: idl.Text
  });
  const CyclesBillingConfigUpdate = idl.Record({
    cycles_per_kinic: idl.Nat64,
    min_update_cycles: idl.Nat64,
    top_up: CyclesTopUpConfig
  });
  const CyclesPurchaseResult = idl.Record({
    block_index: idl.Nat64,
    amount_cycles: idl.Nat64,
    balance_cycles: idl.Nat64
  });
  const CyclesTopUpLauncherError = idl.Variant({
    Unauthorized: idl.Null,
    TooSoon: idl.Null,
    LauncherBalanceTooLow: idl.Null,
    TopUpFailed: idl.Text
  });
  const CyclesTopUpLauncherResult = idl.Variant({ Ok: idl.Null, Err: CyclesTopUpLauncherError });
  const CyclesTopUpCheckStatus = idl.Variant({
    SkippedDisabled: idl.Null,
    CallErr: idl.Null,
    LauncherErr: idl.Null,
    SkippedInProgress: idl.Null,
    LauncherOk: idl.Null,
    SkippedAboveThreshold: idl.Null
  });
  const CyclesTopUpCheckResult = idl.Record({
    balance_cycles_before: idl.Nat,
    balance_cycles_after: idl.Opt(idl.Nat),
    threshold_cycles: idl.Nat,
    called_launcher: idl.Bool,
    status: CyclesTopUpCheckStatus,
    launcher_result: idl.Opt(CyclesTopUpLauncherResult)
  });
  const DatabaseCyclesPendingPurchase = idl.Record({
    operation_id: idl.Nat64,
    database_id: idl.Text,
    status: idl.Text,
    amount_cycles: idl.Nat64,
    payment_amount_e8s: idl.Nat64,
    ledger_block_index: idl.Opt(idl.Nat64),
    created_at_ms: idl.Int64,
    required_action: idl.Text
  });
  const DatabaseCyclesPurchaseRequest = idl.Record({
    database_id: idl.Text,
    payment_amount_e8s: idl.Nat64,
    min_expected_cycles: idl.Nat64
  });
  const MarketCreateListingRequest = idl.Record({
    llm_summary: idl.Opt(idl.Text),
    title: idl.Text,
    description: idl.Text,
    database_id: idl.Text,
    payout_principal: idl.Text,
    price_e8s: idl.Nat64,
    tags_json: idl.Text
  });
  const MarketEntitlement = idl.Record({
    status: idl.Text,
    purchased_at_ms: idl.Int64,
    database_id: idl.Text,
    buyer_principal: idl.Text,
    order_id: idl.Text,
    listing_id: idl.Text
  });
  const MarketEntitlementPage = idl.Record({
    next_cursor: idl.Opt(idl.Text),
    entitlements: idl.Vec(MarketEntitlement)
  });
  const MarketListingStatus = idl.Variant({ Paused: idl.Null, Active: idl.Null });
  const MarketListing = idl.Record({
    status: MarketListingStatus,
    llm_summary: idl.Opt(idl.Text),
    title: idl.Text,
    report_count: idl.Nat64,
    description: idl.Text,
    updated_at_ms: idl.Int64,
    created_at_ms: idl.Int64,
    seller_principal: idl.Text,
    payout_principal: idl.Text,
    purchase_count: idl.Nat64,
    database_id: idl.Text,
    listing_id: idl.Text,
    revision: idl.Nat64,
    price_e8s: idl.Nat64,
    tags_json: idl.Text
  });
  const MarketCategoryGraphEdge = idl.Record({
    source_category: idl.Text,
    target_category: idl.Text,
    link_count: idl.Nat64
  });
  const MarketCategoryGraphNode = idl.Record({ node_count: idl.Nat64, category: idl.Text });
  const MarketCategoryGraph = idl.Record({
    nodes: idl.Vec(MarketCategoryGraphNode),
    edges: idl.Vec(MarketCategoryGraphEdge)
  });
  const LinkEdge = idl.Record({
    updated_at: idl.Int64,
    link_kind: idl.Text,
    link_text: idl.Text,
    source_path: idl.Text,
    raw_href: idl.Text,
    target_path: idl.Text
  });
  const MarketListingPage = idl.Record({ listings: idl.Vec(MarketListing), next_cursor: idl.Opt(idl.Text) });
  const MarketOrder = idl.Record({
    created_at_ms: idl.Int64,
    seller_principal: idl.Text,
    payout_principal: idl.Text,
    database_id: idl.Text,
    buyer_principal: idl.Text,
    order_id: idl.Text,
    listing_id: idl.Text,
    ledger_block_index: idl.Nat64,
    price_e8s: idl.Nat64
  });
  const MarketOrderPage = idl.Record({ orders: idl.Vec(MarketOrder), next_cursor: idl.Opt(idl.Text) });
  const MarketPreviewExcerpt = idl.Record({
    path: idl.Text,
    etag: idl.Text,
    excerpt: idl.Text,
    content_chars: idl.Nat64
  });
  const MarketListingPreview = idl.Record({
    top_level_paths: idl.Vec(idl.Text),
    excerpts: idl.Vec(MarketPreviewExcerpt),
    category_graph: MarketCategoryGraph,
    graph_links: idl.Vec(LinkEdge),
    preview_stale: idl.Bool
  });
  const MarketListingVerifiedStats = idl.Record({
    source_chars: idl.Nat64,
    total_nodes: idl.Nat64,
    logical_size_bytes: idl.Nat64,
    link_edges: idl.Nat64,
    wiki_nodes: idl.Nat64,
    source_nodes: idl.Nat64,
    markdown_chars: idl.Nat64,
    last_content_updated_at_ms: idl.Opt(idl.Int64),
    folder_nodes: idl.Nat64
  });
  const MarketListingDetail = idl.Record({
    listing: MarketListing,
    preview: MarketListingPreview,
    verified_stats: MarketListingVerifiedStats
  });
  const MarketPurchasePreview = idl.Record({
    already_entitled: idl.Bool,
    database_id: idl.Text,
    listing_id: idl.Text,
    price_e8s: idl.Nat64
  });
  const MarketPurchaseRequest = idl.Record({ listing_id: idl.Text, price_e8s: idl.Nat64, access_principal: idl.Text });
  const MarketUpdateListingRequest = idl.Record({
    llm_summary: idl.Opt(idl.Text),
    title: idl.Text,
    description: idl.Text,
    listing_id: idl.Text,
    expected_revision: idl.Nat64,
    payout_principal: idl.Text,
    price_e8s: idl.Nat64,
    tags_json: idl.Text
  });
  const Icrc21ConsentMessageMetadata = idl.Record({ utc_offset_minutes: idl.Opt(idl.Int16), language: idl.Text });
  const Icrc21DeviceSpec = idl.Variant({ GenericDisplay: idl.Null, FieldsDisplay: idl.Null });
  const Icrc21ConsentMessageSpec = idl.Record({
    metadata: Icrc21ConsentMessageMetadata,
    device_spec: idl.Opt(Icrc21DeviceSpec)
  });
  const Icrc21ConsentMessageRequest = idl.Record({
    arg: idl.Vec(idl.Nat8),
    method: idl.Text,
    user_preferences: Icrc21ConsentMessageSpec
  });
  const Icrc21ConsentMessage = idl.Variant({ GenericDisplayMessage: idl.Text });
  const Icrc21ConsentInfo = idl.Record({
    metadata: Icrc21ConsentMessageMetadata,
    consent_message: Icrc21ConsentMessage
  });
  const Icrc21ErrorInfo = idl.Record({ description: idl.Text });
  const Icrc21GenericError = idl.Record({ description: idl.Text, error_code: idl.Nat });
  const Icrc21Error = idl.Variant({
    GenericError: Icrc21GenericError,
    InsufficientPayment: Icrc21ErrorInfo,
    UnsupportedCanisterCall: Icrc21ErrorInfo,
    ConsentMessageUnavailable: Icrc21ErrorInfo
  });
  const Icrc21ConsentMessageResponse = idl.Variant({ Ok: Icrc21ConsentInfo, Err: Icrc21Error });
  const Icrc10SupportedStandard = idl.Record({ url: idl.Text, name: idl.Text });
  const CreateDatabaseRequest = idl.Record({ name: idl.Text });
  const CreateDatabaseResult = idl.Record({ name: idl.Text, database_id: idl.Text });
  const RenameDatabaseRequest = idl.Record({ name: idl.Text, database_id: idl.Text });
  const DatabaseIdRequest = idl.Record({ database_id: idl.Text });
  const DatabaseMember = idl.Record({
    principal: idl.Text,
    role: DatabaseRole,
    created_at_ms: idl.Int64,
    database_id: idl.Text
  });
  const DatabaseCycleEntry = idl.Record({
    method: idl.Opt(idl.Text),
    cycles_per_kinic: idl.Opt(idl.Nat64),
    payment_amount_e8s: idl.Opt(idl.Nat64),
    kind: idl.Text,
    created_at_ms: idl.Int64,
    amount_cycles: idl.Int64,
    ledger_block_index: idl.Opt(idl.Nat64),
    database_id: idl.Text,
    balance_after_cycles: idl.Nat64,
    caller: idl.Text,
    cycles_delta: idl.Opt(idl.Nat64),
    entry_id: idl.Nat64
  });
  const DatabaseCycleEntryPage = idl.Record({ entries: idl.Vec(DatabaseCycleEntry), next_cursor: idl.Opt(idl.Nat64) });
  const NodeKind = idl.Variant({ File: idl.Null, Source: idl.Null, Folder: idl.Null });
  const NodeEntryKind = idl.Variant({ File: idl.Null, Source: idl.Null, Directory: idl.Null, Folder: idl.Null });
  const Node = idl.Record({
    updated_at: idl.Int64,
    content: idl.Text,
    etag: idl.Text,
    kind: NodeKind,
    path: idl.Text,
    created_at: idl.Int64,
    metadata_json: idl.Text
  });
  const ChildNode = idl.Record({
    updated_at: idl.Opt(idl.Int64),
    etag: idl.Opt(idl.Text),
    kind: NodeEntryKind,
    name: idl.Text,
    size_bytes: idl.Opt(idl.Nat64),
    path: idl.Text,
    has_children: idl.Bool,
    is_virtual: idl.Bool
  });
  const NodeMutationAck = idl.Record({ updated_at: idl.Int64, etag: idl.Text, kind: NodeKind, path: idl.Text });
  const NodeContext = idl.Record({ incoming_links: idl.Vec(LinkEdge), node: Node, outgoing_links: idl.Vec(LinkEdge) });
  const SearchPreviewField = idl.Variant({ Path: idl.Null, Content: idl.Null });
  const SearchPreviewMode = idl.Variant({ Light: idl.Null, ContentStart: idl.Null, None: idl.Null });
  const SearchPreview = idl.Record({
    field: SearchPreviewField,
    char_offset: idl.Nat32,
    match_reason: idl.Text,
    excerpt: idl.Opt(idl.Text)
  });
  const SearchNodeHit = idl.Record({
    preview: idl.Opt(SearchPreview),
    kind: NodeKind,
    path: idl.Text,
    match_reasons: idl.Vec(idl.Text),
    snippet: idl.Opt(idl.Text),
    score: idl.Float32
  });
  const MemoryCapability = idl.Record({ name: idl.Text, description: idl.Text });
  const MemoryRoot = idl.Record({ kind: idl.Text, path: idl.Text });
  const CanonicalRole = idl.Record({ name: idl.Text, path_pattern: idl.Text, purpose: idl.Text });
  const MemoryManifest = idl.Record({
    api_version: idl.Text,
    budget_unit: idl.Text,
    capabilities: idl.Vec(MemoryCapability),
    enabled_stores: idl.Vec(idl.Text),
    entry_roots: idl.Vec(MemoryRoot),
    max_depth: idl.Nat32,
    max_query_limit: idl.Nat32,
    recommended_entrypoint: idl.Text,
    write_policy: idl.Text,
    canonical_roles: idl.Vec(CanonicalRole),
    purpose: idl.Text,
    roots: idl.Vec(MemoryRoot)
  });
  const SourceEvidenceRef = idl.Record({
    link_text: idl.Text,
    via_path: idl.Text,
    source_content_hash: idl.Opt(idl.Text),
    source_path: idl.Text,
    source_updated_at: idl.Opt(idl.Int64),
    source_etag: idl.Opt(idl.Text),
    raw_href: idl.Text
  });
  const SourceEvidence = idl.Record({ node_path: idl.Text, refs: idl.Vec(SourceEvidenceRef) });
  const QueryContext = idl.Record({
    truncated: idl.Bool,
    task: idl.Text,
    evidence: idl.Vec(SourceEvidence),
    nodes: idl.Vec(NodeContext),
    graph_links: idl.Vec(LinkEdge),
    search_hits: idl.Vec(SearchNodeHit),
    namespace: idl.Text
  });
  const ListChildrenRequest = idl.Record({ path: idl.Text, database_id: idl.Text });
  const IncomingLinksRequest = idl.Record({ path: idl.Text, limit: idl.Nat32, database_id: idl.Text });
  const OutgoingLinksRequest = idl.Record({ path: idl.Text, limit: idl.Nat32, database_id: idl.Text });
  const IndexSqlJsonQueryResult = idl.Record({ rows: idl.Vec(idl.Text), row_count: idl.Nat32, limit: idl.Nat32 });
  const WikiMetrics = idl.Record({
    users_total: idl.Nat64,
    users_active_30d: idl.Nat64,
    users_new_30d: idl.Nat64,
    databases_total: idl.Nat64,
    databases_active_30d: idl.Nat64,
    databases_new_30d: idl.Nat64,
    paid_users_total: idl.Nat64,
    charged_kinic_total_e8s: idl.Nat64,
    charged_kinic_30d_e8s: idl.Nat64,
    last_activity_at_ms: idl.Opt(idl.Int64)
  });
  const WikiMetricsPoint = idl.Record({ bucket_start_ms: idl.Int64, metrics: WikiMetrics });
  const GraphLinksRequest = idl.Record({ limit: idl.Nat32, database_id: idl.Text, prefix: idl.Text });
  const GraphNeighborhoodRequest = idl.Record({
    center_path: idl.Text,
    limit: idl.Nat32,
    database_id: idl.Text,
    depth: idl.Nat32
  });
  const NodeContextRequest = idl.Record({ link_limit: idl.Nat32, path: idl.Text, database_id: idl.Text });
  const WriteNodeRequest = idl.Record({
    content: idl.Text,
    kind: NodeKind,
    path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    metadata_json: idl.Text,
    database_id: idl.Text
  });
  const WriteSourceForGenerationRequest = idl.Record({
    content: idl.Text,
    path: idl.Text,
    session_nonce: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    metadata_json: idl.Text,
    database_id: idl.Text
  });
  const DeleteNodeRequest = idl.Record({
    path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    expected_folder_index_etag: idl.Opt(idl.Text),
    database_id: idl.Text
  });
  const MkdirNodeRequest = idl.Record({ path: idl.Text, database_id: idl.Text });
  const MoveNodeRequest = idl.Record({
    from_path: idl.Text,
    to_path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    overwrite: idl.Bool,
    database_id: idl.Text
  });
  const UrlIngestTriggerSessionRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const UrlIngestTriggerSessionCheckRequest = idl.Record({
    database_id: idl.Text,
    request_path: idl.Text,
    session_nonce: idl.Text
  });
  const OpsAnswerSessionRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const OpsAnswerSessionCheckRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const OpsAnswerSessionCheckResult = idl.Record({ principal: idl.Text });
  const SourceRunSessionCheckRequest = idl.Record({
    source_path: idl.Text,
    source_etag: idl.Text,
    session_nonce: idl.Text,
    database_id: idl.Text
  });
  const SearchNodePathsRequest = idl.Record({
    top_k: idl.Nat32,
    database_id: idl.Text,
    preview_mode: idl.Opt(SearchPreviewMode),
    prefix: idl.Opt(idl.Text),
    query_text: idl.Text
  });
  const SearchNodesRequest = idl.Record({
    top_k: idl.Nat32,
    database_id: idl.Text,
    preview_mode: idl.Opt(SearchPreviewMode),
    prefix: idl.Opt(idl.Text),
    query_text: idl.Text
  });
  const QueryContextRequest = idl.Record({
    task: idl.Text,
    include_evidence: idl.Bool,
    entities: idl.Vec(idl.Text),
    budget_tokens: idl.Nat32,
    database_id: idl.Text,
    depth: idl.Nat32,
    namespace: idl.Opt(idl.Text)
  });
  const SourceEvidenceRequest = idl.Record({ node_path: idl.Text, database_id: idl.Text });
  const StorageBillingBatchRequest = idl.Record({ limit: idl.Opt(idl.Nat32), cursor_mount_id: idl.Opt(idl.Nat16) });
  const StorageBillingBatchResult = idl.Record({
    paid_cycles: idl.Nat64,
    suspended_databases: idl.Nat32,
    next_cursor_mount_id: idl.Opt(idl.Nat16),
    charged_databases: idl.Nat32,
    processed_databases: idl.Nat32
  });
  const ResultNode = idl.Variant({ Ok: idl.Opt(Node), Err: idl.Text });
  const ResultChildren = idl.Variant({ Ok: idl.Vec(ChildNode), Err: idl.Text });
  const ResultLinks = idl.Variant({ Ok: idl.Vec(LinkEdge), Err: idl.Text });
  const ResultNodeContext = idl.Variant({ Ok: idl.Opt(NodeContext), Err: idl.Text });
  const ResultSearch = idl.Variant({ Ok: idl.Vec(SearchNodeHit), Err: idl.Text });
  const ResultQueryContext = idl.Variant({ Ok: QueryContext, Err: idl.Text });
  const ResultIndexSqlJsonQuery = idl.Variant({ Ok: IndexSqlJsonQueryResult, Err: idl.Text });
  const ResultWikiMetrics = idl.Variant({ Ok: WikiMetrics, Err: idl.Text });
  const ResultWikiMetricsSeries = idl.Variant({ Ok: idl.Vec(WikiMetricsPoint), Err: idl.Text });
  const ResultSourceEvidence = idl.Variant({ Ok: SourceEvidence, Err: idl.Text });
  const ResultStorageBillingBatch = idl.Variant({ Ok: StorageBillingBatchResult, Err: idl.Text });
  const ResultMemoryManifest = idl.Variant({ Ok: MemoryManifest, Err: idl.Text });
  const ResultCyclesTopUpCheck = idl.Variant({ Ok: CyclesTopUpCheckResult, Err: idl.Text });
  const ResultCreateDatabase = idl.Variant({ Ok: CreateDatabaseResult, Err: idl.Text });
  const ResultCyclesBillingConfig = idl.Variant({ Ok: CyclesBillingConfig, Err: idl.Text });
  const ResultCyclesPurchase = idl.Variant({ Ok: CyclesPurchaseResult, Err: idl.Text });
  const ResultCyclesEntries = idl.Variant({ Ok: DatabaseCycleEntryPage, Err: idl.Text });
  const ResultCyclesPendingPurchases = idl.Variant({ Ok: idl.Vec(DatabaseCyclesPendingPurchase), Err: idl.Text });
  const ResultMarketEntitlementPage = idl.Variant({ Ok: MarketEntitlementPage, Err: idl.Text });
  const ResultMarketListing = idl.Variant({ Ok: MarketListing, Err: idl.Text });
  const ResultMarketListingDetail = idl.Variant({ Ok: MarketListingDetail, Err: idl.Text });
  const ResultMarketListings = idl.Variant({ Ok: idl.Vec(MarketListing), Err: idl.Text });
  const ResultMarketListingPage = idl.Variant({ Ok: MarketListingPage, Err: idl.Text });
  const ResultMarketOrder = idl.Variant({ Ok: MarketOrder, Err: idl.Text });
  const ResultMarketOrderPage = idl.Variant({ Ok: MarketOrderPage, Err: idl.Text });
  const ResultMarketPurchasePreview = idl.Variant({ Ok: MarketPurchasePreview, Err: idl.Text });
  const ResultDatabases = idl.Variant({ Ok: idl.Vec(DatabaseSummary), Err: idl.Text });
  const ResultMembers = idl.Variant({ Ok: idl.Vec(DatabaseMember), Err: idl.Text });
  const ResultNat64 = idl.Variant({ Ok: idl.Nat64, Err: idl.Text });
  const WriteNodeResult = idl.Record({ created: idl.Bool, node: NodeMutationAck });
  const ResultWriteNode = idl.Variant({ Ok: WriteNodeResult, Err: idl.Text });
  const WriteSourceForGenerationResult = idl.Record({ session_nonce: idl.Text, write: WriteNodeResult });
  const ResultWriteSourceForGeneration = idl.Variant({ Ok: WriteSourceForGenerationResult, Err: idl.Text });
  const DeleteNodeResult = idl.Record({ path: idl.Text });
  const ResultDeleteNode = idl.Variant({ Ok: DeleteNodeResult, Err: idl.Text });
  const MkdirNodeResult = idl.Record({ path: idl.Text, created: idl.Bool });
  const ResultMkdirNode = idl.Variant({ Ok: MkdirNodeResult, Err: idl.Text });
  const MoveNodeResult = idl.Record({ from_path: idl.Text, node: NodeMutationAck, overwrote: idl.Bool });
  const ResultMoveNode = idl.Variant({ Ok: MoveNodeResult, Err: idl.Text });
  const ResultUnit = idl.Variant({ Ok: idl.Null, Err: idl.Text });
  const ResultOpsAnswerSessionCheck = idl.Variant({ Ok: OpsAnswerSessionCheckResult, Err: idl.Text });

  return idl.Service({
    // The public canister ABI keeps legacy ops_* names; browser code exposes Query Q&A wrappers.
    authorize_ops_answer_session: idl.Func([OpsAnswerSessionRequest], [ResultUnit], []),
    authorize_url_ingest_trigger_session: idl.Func([UrlIngestTriggerSessionRequest], [ResultUnit], []),
    canister_health: idl.Func([], [CanisterHealth], ["query"]),
    check_database_write_cycles: idl.Func([idl.Text], [ResultUnit], ["query"]),
    check_cycles_top_up: idl.Func([], [ResultCyclesTopUpCheck], []),
    check_ops_answer_session: idl.Func([OpsAnswerSessionCheckRequest], [ResultOpsAnswerSessionCheck], ["query"]),
    check_source_run_session: idl.Func([SourceRunSessionCheckRequest], [ResultUnit], ["query"]),
    check_url_ingest_trigger_session: idl.Func([UrlIngestTriggerSessionCheckRequest], [ResultUnit], ["query"]),
    create_database: idl.Func([CreateDatabaseRequest], [ResultCreateDatabase], []),
    delete_database: idl.Func([DatabaseIdRequest], [ResultUnit], []),
    delete_node: idl.Func([DeleteNodeRequest], [ResultDeleteNode], []),
    get_cycles_billing_config: idl.Func([], [ResultCyclesBillingConfig], ["query"]),
    grant_database_access: idl.Func([idl.Text, idl.Text, DatabaseRole], [ResultUnit], []),
    graph_links: idl.Func([GraphLinksRequest], [ResultLinks], ["query"]),
    graph_neighborhood: idl.Func([GraphNeighborhoodRequest], [ResultLinks], ["query"]),
    icrc10_supported_standards: idl.Func([], [idl.Vec(Icrc10SupportedStandard)], ["query"]),
    icrc21_canister_call_consent_message: idl.Func([Icrc21ConsentMessageRequest], [Icrc21ConsentMessageResponse], []),
    incoming_links: idl.Func([IncomingLinksRequest], [ResultLinks], ["query"]),
    list_database_cycle_entries: idl.Func([idl.Text, idl.Opt(idl.Nat64), idl.Nat32], [ResultCyclesEntries], ["query"]),
    list_database_cycles_pending_purchases: idl.Func([idl.Text], [ResultCyclesPendingPurchases], ["query"]),
    list_databases: idl.Func([], [ResultDatabases], ["query"]),
    list_database_members: idl.Func([idl.Text], [ResultMembers], ["query"]),
    market_count_active_entitlements: idl.Func([idl.Text], [ResultNat64], ["query"]),
    market_create_listing: idl.Func([MarketCreateListingRequest], [ResultMarketListing], []),
    market_get_listing: idl.Func([idl.Text], [ResultMarketListingDetail], ["query"]),
    market_list_database_entitlements: idl.Func([idl.Text, idl.Opt(idl.Text), idl.Nat32], [ResultMarketEntitlementPage], ["query"]),
    market_list_database_listings: idl.Func([idl.Text], [ResultMarketListings], ["query"]),
    market_list_entitlements: idl.Func([idl.Opt(idl.Text), idl.Nat32], [ResultMarketEntitlementPage], ["query"]),
    market_list_listings: idl.Func([idl.Opt(idl.Text), idl.Nat32], [ResultMarketListingPage], ["query"]),
    market_list_orders: idl.Func([idl.Opt(idl.Text), idl.Nat32], [ResultMarketOrderPage], ["query"]),
    market_list_seller_listings: idl.Func([idl.Text, idl.Opt(idl.Text), idl.Nat32], [ResultMarketListingPage], ["query"]),
    market_pause_listing: idl.Func([idl.Text], [ResultMarketListing], []),
    market_preview_purchase: idl.Func([idl.Text], [ResultMarketPurchasePreview], ["query"]),
    market_publish_listing: idl.Func([idl.Text], [ResultMarketListing], []),
    market_purchase_access: idl.Func([MarketPurchaseRequest], [ResultMarketOrder], []),
    market_update_listing: idl.Func([MarketUpdateListingRequest], [ResultMarketListing], []),
    memory_manifest: idl.Func([DatabaseIdRequest], [ResultMemoryManifest], ["query"]),
    mkdir_node: idl.Func([MkdirNodeRequest], [ResultMkdirNode], []),
    move_node: idl.Func([MoveNodeRequest], [ResultMoveNode], []),
    query_context: idl.Func([QueryContextRequest], [ResultQueryContext], ["query"]),
    query_database_sql_json: idl.Func([idl.Text, idl.Text, idl.Nat32], [ResultIndexSqlJsonQuery], ["query"]),
    query_index_sql_json: idl.Func([idl.Text, idl.Nat32], [ResultIndexSqlJsonQuery], ["query"]),
    read_node: idl.Func([idl.Text, idl.Text], [ResultNode], ["query"]),
    read_node_context: idl.Func([NodeContextRequest], [ResultNodeContext], ["query"]),
    list_children: idl.Func([ListChildrenRequest], [ResultChildren], ["query"]),
    outgoing_links: idl.Func([OutgoingLinksRequest], [ResultLinks], ["query"]),
    revoke_database_access: idl.Func([idl.Text, idl.Text], [ResultUnit], []),
    rename_database: idl.Func([RenameDatabaseRequest], [ResultUnit], []),
    search_node_paths: idl.Func([SearchNodePathsRequest], [ResultSearch], ["query"]),
    search_nodes: idl.Func([SearchNodesRequest], [ResultSearch], ["query"]),
    settle_database_storage_charges_batch: idl.Func([StorageBillingBatchRequest], [ResultStorageBillingBatch], []),
    source_evidence: idl.Func([SourceEvidenceRequest], [ResultSourceEvidence], ["query"]),
    update_cycles_billing_config: idl.Func([CyclesBillingConfigUpdate], [ResultUnit], []),
    wiki_metrics: idl.Func([], [ResultWikiMetrics], ["query"]),
    wiki_metrics_series: idl.Func([idl.Nat32], [ResultWikiMetricsSeries], ["query"]),
    purchase_database_cycles: idl.Func([DatabaseCyclesPurchaseRequest], [ResultCyclesPurchase], []),
    write_node: idl.Func([WriteNodeRequest], [ResultWriteNode], []),
    write_source_for_generation: idl.Func([WriteSourceForGenerationRequest], [ResultWriteSourceForGeneration], [])
  });
};
