// Generated by scripts/generate-vfs-idl.mjs from crates/vfs_canister/vfs.did.
// Do not edit by hand.
import { Actor } from "@icp-sdk/core/agent";
import { IDL } from "@icp-sdk/core/candid";

type ActorInterfaceFactory = Parameters<typeof Actor.createActor>[0];

export const idlFactory: ActorInterfaceFactory = ({ IDL: idl }) => {
  const CanisterHealth = idl.Record({ cycles_balance: idl.Nat });
  const DatabaseRole = idl.Variant({ Reader: idl.Null, Writer: idl.Null, Owner: idl.Null });
  const DatabaseStatus = idl.Variant({
    Hot: idl.Null,
    Pending: idl.Null,
    Active: idl.Null,
    Restoring: idl.Null,
    Archiving: idl.Null,
    Archived: idl.Null
  });
  const DatabaseSummary = idl.Record({
    status: DatabaseStatus,
    role: DatabaseRole,
    logical_size_bytes: idl.Nat64,
    database_id: idl.Text,
    name: idl.Text,
    credits_balance: idl.Opt(idl.Nat64),
    credits_suspended_at_ms: idl.Opt(idl.Int64),
    archived_at_ms: idl.Opt(idl.Int64)
  });
  const CreditsConfig = idl.Record({
    credits_per_kinic: idl.Nat64,
    min_update_credits: idl.Nat64,
    cycles_per_credit: idl.Nat64,
    kinic_ledger_canister_id: idl.Text,
    sns_governance_id: idl.Text
  });
  const CreditsPurchaseResult = idl.Record({ block_index: idl.Nat64, balance_credits: idl.Nat64 });
  const CreateDatabaseRequest = idl.Record({ name: idl.Text });
  const CreateDatabaseResult = idl.Record({ name: idl.Text, database_id: idl.Text });
  const RenameDatabaseRequest = idl.Record({ name: idl.Text, database_id: idl.Text });
  const DeleteDatabaseRequest = idl.Record({ database_id: idl.Text });
  const DatabaseMember = idl.Record({
    principal: idl.Text,
    role: DatabaseRole,
    created_at_ms: idl.Int64,
    database_id: idl.Text
  });
  const DatabaseCreditEntry = idl.Record({
    method: idl.Opt(idl.Text),
    credits_per_kinic: idl.Opt(idl.Nat64),
    payment_amount_e8s: idl.Opt(idl.Nat64),
    kind: idl.Text,
    cycles_per_credit: idl.Opt(idl.Nat64),
    created_at_ms: idl.Int64,
    amount_credits: idl.Int64,
    ledger_block_index: idl.Opt(idl.Nat64),
    database_id: idl.Text,
    balance_after_credits: idl.Nat64,
    caller: idl.Text,
    cycles_delta: idl.Opt(idl.Nat64),
    entry_id: idl.Nat64
  });
  const DatabaseCreditEntryPage = idl.Record({
    entries: idl.Vec(DatabaseCreditEntry),
    next_cursor: idl.Opt(idl.Nat64)
  });
  const DatabaseCreditPendingOperation = idl.Record({
    credits: idl.Int64,
    payment_amount_e8s: idl.Int64,
    to_owner: idl.Opt(idl.Text),
    to_subaccount: idl.Opt(idl.Vec(idl.Nat8)),
    from_owner: idl.Opt(idl.Text),
    kind: idl.Text,
    operation_id: idl.Nat64,
    from_subaccount: idl.Opt(idl.Vec(idl.Nat8)),
    created_at_ms: idl.Int64,
    ledger_fee_e8s: idl.Opt(idl.Int64),
    ledger_created_at_time_ns: idl.Opt(idl.Int64),
    database_id: idl.Text,
    caller: idl.Text
  });
  const DatabaseCreditPendingOperationPage = idl.Record({
    entries: idl.Vec(DatabaseCreditPendingOperation),
    next_cursor: idl.Opt(idl.Nat64)
  });
  const NodeKind = idl.Variant({ File: idl.Null, Source: idl.Null, Folder: idl.Null });
  const NodeEntryKind = idl.Variant({ File: idl.Null, Source: idl.Null, Directory: idl.Null, Folder: idl.Null });
  const Node = idl.Record({
    updated_at: idl.Int64,
    content: idl.Text,
    etag: idl.Text,
    kind: NodeKind,
    path: idl.Text,
    created_at: idl.Int64,
    metadata_json: idl.Text
  });
  const ChildNode = idl.Record({
    updated_at: idl.Opt(idl.Int64),
    etag: idl.Opt(idl.Text),
    kind: NodeEntryKind,
    name: idl.Text,
    size_bytes: idl.Opt(idl.Nat64),
    path: idl.Text,
    has_children: idl.Bool,
    is_virtual: idl.Bool
  });
  const NodeMutationAck = idl.Record({ updated_at: idl.Int64, etag: idl.Text, kind: NodeKind, path: idl.Text });
  const LinkEdge = idl.Record({
    updated_at: idl.Int64,
    link_kind: idl.Text,
    link_text: idl.Text,
    source_path: idl.Text,
    raw_href: idl.Text,
    target_path: idl.Text
  });
  const NodeContext = idl.Record({ incoming_links: idl.Vec(LinkEdge), node: Node, outgoing_links: idl.Vec(LinkEdge) });
  const SearchPreviewField = idl.Variant({ Path: idl.Null, Content: idl.Null });
  const SearchPreviewMode = idl.Variant({ Light: idl.Null, ContentStart: idl.Null, None: idl.Null });
  const SearchPreview = idl.Record({
    field: SearchPreviewField,
    char_offset: idl.Nat32,
    match_reason: idl.Text,
    excerpt: idl.Opt(idl.Text)
  });
  const SearchNodeHit = idl.Record({
    preview: idl.Opt(SearchPreview),
    kind: NodeKind,
    path: idl.Text,
    match_reasons: idl.Vec(idl.Text),
    snippet: idl.Opt(idl.Text),
    score: idl.Float32
  });
  const MemoryCapability = idl.Record({ name: idl.Text, description: idl.Text });
  const MemoryRoot = idl.Record({ kind: idl.Text, path: idl.Text });
  const CanonicalRole = idl.Record({ name: idl.Text, path_pattern: idl.Text, purpose: idl.Text });
  const MemoryManifest = idl.Record({
    api_version: idl.Text,
    budget_unit: idl.Text,
    capabilities: idl.Vec(MemoryCapability),
    max_depth: idl.Nat32,
    max_query_limit: idl.Nat32,
    recommended_entrypoint: idl.Text,
    write_policy: idl.Text,
    canonical_roles: idl.Vec(CanonicalRole),
    purpose: idl.Text,
    roots: idl.Vec(MemoryRoot)
  });
  const SourceEvidenceRef = idl.Record({
    link_text: idl.Text,
    via_path: idl.Text,
    source_path: idl.Text,
    raw_href: idl.Text
  });
  const SourceEvidence = idl.Record({ node_path: idl.Text, refs: idl.Vec(SourceEvidenceRef) });
  const QueryContext = idl.Record({
    truncated: idl.Bool,
    task: idl.Text,
    evidence: idl.Vec(SourceEvidence),
    nodes: idl.Vec(NodeContext),
    graph_links: idl.Vec(LinkEdge),
    search_hits: idl.Vec(SearchNodeHit),
    namespace: idl.Text
  });
  const ListChildrenRequest = idl.Record({ path: idl.Text, database_id: idl.Text });
  const IncomingLinksRequest = idl.Record({ path: idl.Text, limit: idl.Nat32, database_id: idl.Text });
  const OutgoingLinksRequest = idl.Record({ path: idl.Text, limit: idl.Nat32, database_id: idl.Text });
  const GraphLinksRequest = idl.Record({ limit: idl.Nat32, database_id: idl.Text, prefix: idl.Text });
  const GraphNeighborhoodRequest = idl.Record({
    center_path: idl.Text,
    limit: idl.Nat32,
    database_id: idl.Text,
    depth: idl.Nat32
  });
  const NodeContextRequest = idl.Record({ link_limit: idl.Nat32, path: idl.Text, database_id: idl.Text });
  const WriteNodeRequest = idl.Record({
    content: idl.Text,
    kind: NodeKind,
    path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    metadata_json: idl.Text,
    database_id: idl.Text
  });
  const WriteSourceForGenerationRequest = idl.Record({
    content: idl.Text,
    path: idl.Text,
    session_nonce: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    metadata_json: idl.Text,
    database_id: idl.Text
  });
  const DeleteNodeRequest = idl.Record({
    path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    expected_folder_index_etag: idl.Opt(idl.Text),
    database_id: idl.Text
  });
  const MkdirNodeRequest = idl.Record({ path: idl.Text, database_id: idl.Text });
  const MoveNodeRequest = idl.Record({
    from_path: idl.Text,
    to_path: idl.Text,
    expected_etag: idl.Opt(idl.Text),
    overwrite: idl.Bool,
    database_id: idl.Text
  });
  const UrlIngestTriggerSessionRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const UrlIngestTriggerSessionCheckRequest = idl.Record({
    database_id: idl.Text,
    request_path: idl.Text,
    session_nonce: idl.Text
  });
  const OpsAnswerSessionRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const OpsAnswerSessionCheckRequest = idl.Record({ database_id: idl.Text, session_nonce: idl.Text });
  const OpsAnswerSessionCheckResult = idl.Record({ principal: idl.Text });
  const SourceRunSessionCheckRequest = idl.Record({
    source_path: idl.Text,
    source_etag: idl.Text,
    session_nonce: idl.Text,
    database_id: idl.Text
  });
  const SearchNodePathsRequest = idl.Record({
    top_k: idl.Nat32,
    database_id: idl.Text,
    preview_mode: idl.Opt(SearchPreviewMode),
    prefix: idl.Opt(idl.Text),
    query_text: idl.Text
  });
  const SearchNodesRequest = idl.Record({
    top_k: idl.Nat32,
    database_id: idl.Text,
    preview_mode: idl.Opt(SearchPreviewMode),
    prefix: idl.Opt(idl.Text),
    query_text: idl.Text
  });
  const QueryContextRequest = idl.Record({
    task: idl.Text,
    include_evidence: idl.Bool,
    entities: idl.Vec(idl.Text),
    budget_tokens: idl.Nat32,
    database_id: idl.Text,
    depth: idl.Nat32,
    namespace: idl.Opt(idl.Text)
  });
  const SourceEvidenceRequest = idl.Record({ node_path: idl.Text, database_id: idl.Text });
  const ResultNode = idl.Variant({ Ok: idl.Opt(Node), Err: idl.Text });
  const ResultChildren = idl.Variant({ Ok: idl.Vec(ChildNode), Err: idl.Text });
  const ResultLinks = idl.Variant({ Ok: idl.Vec(LinkEdge), Err: idl.Text });
  const ResultNodeContext = idl.Variant({ Ok: idl.Opt(NodeContext), Err: idl.Text });
  const ResultSearch = idl.Variant({ Ok: idl.Vec(SearchNodeHit), Err: idl.Text });
  const ResultQueryContext = idl.Variant({ Ok: QueryContext, Err: idl.Text });
  const ResultSourceEvidence = idl.Variant({ Ok: SourceEvidence, Err: idl.Text });
  const ResultCreateDatabase = idl.Variant({ Ok: CreateDatabaseResult, Err: idl.Text });
  const ResultCreditsConfig = idl.Variant({ Ok: CreditsConfig, Err: idl.Text });
  const ResultCreditsPurchase = idl.Variant({ Ok: CreditsPurchaseResult, Err: idl.Text });
  const ResultCreditsEntries = idl.Variant({ Ok: DatabaseCreditEntryPage, Err: idl.Text });
  const ResultCreditsPending = idl.Variant({ Ok: DatabaseCreditPendingOperationPage, Err: idl.Text });
  const ResultDatabases = idl.Variant({ Ok: idl.Vec(DatabaseSummary), Err: idl.Text });
  const ResultMembers = idl.Variant({ Ok: idl.Vec(DatabaseMember), Err: idl.Text });
  const WriteNodeResult = idl.Record({ created: idl.Bool, node: NodeMutationAck });
  const ResultWriteNode = idl.Variant({ Ok: WriteNodeResult, Err: idl.Text });
  const WriteSourceForGenerationResult = idl.Record({ session_nonce: idl.Text, write: WriteNodeResult });
  const ResultWriteSourceForGeneration = idl.Variant({ Ok: WriteSourceForGenerationResult, Err: idl.Text });
  const DeleteNodeResult = idl.Record({ path: idl.Text });
  const ResultDeleteNode = idl.Variant({ Ok: DeleteNodeResult, Err: idl.Text });
  const MkdirNodeResult = idl.Record({ path: idl.Text, created: idl.Bool });
  const ResultMkdirNode = idl.Variant({ Ok: MkdirNodeResult, Err: idl.Text });
  const MoveNodeResult = idl.Record({ from_path: idl.Text, node: NodeMutationAck, overwrote: idl.Bool });
  const ResultMoveNode = idl.Variant({ Ok: MoveNodeResult, Err: idl.Text });
  const ResultUnit = idl.Variant({ Ok: idl.Null, Err: idl.Text });
  const ResultOpsAnswerSessionCheck = idl.Variant({ Ok: OpsAnswerSessionCheckResult, Err: idl.Text });

  return idl.Service({
    // The public canister ABI keeps legacy ops_* names; browser code exposes Query Q&A wrappers.
    authorize_ops_answer_session: idl.Func([OpsAnswerSessionRequest], [ResultUnit], []),
    authorize_url_ingest_trigger_session: idl.Func([UrlIngestTriggerSessionRequest], [ResultUnit], []),
    canister_health: idl.Func([], [CanisterHealth], ["query"]),
    check_database_write_credits: idl.Func([idl.Text], [ResultUnit], ["query"]),
    check_ops_answer_session: idl.Func([OpsAnswerSessionCheckRequest], [ResultOpsAnswerSessionCheck], ["query"]),
    check_source_run_session: idl.Func([SourceRunSessionCheckRequest], [ResultUnit], ["query"]),
    check_url_ingest_trigger_session: idl.Func([UrlIngestTriggerSessionCheckRequest], [ResultUnit], ["query"]),
    create_database: idl.Func([CreateDatabaseRequest], [ResultCreateDatabase], []),
    delete_database: idl.Func([DeleteDatabaseRequest], [ResultUnit], []),
    delete_node: idl.Func([DeleteNodeRequest], [ResultDeleteNode], []),
    get_credits_config: idl.Func([], [ResultCreditsConfig], ["query"]),
    grant_database_access: idl.Func([idl.Text, idl.Text, DatabaseRole], [ResultUnit], []),
    graph_links: idl.Func([GraphLinksRequest], [ResultLinks], ["query"]),
    graph_neighborhood: idl.Func([GraphNeighborhoodRequest], [ResultLinks], ["query"]),
    incoming_links: idl.Func([IncomingLinksRequest], [ResultLinks], ["query"]),
    list_database_credit_entries: idl.Func([idl.Text, idl.Opt(idl.Nat64), idl.Nat32], [ResultCreditsEntries], ["query"]),
    list_database_credit_pending_operations: idl.Func([idl.Text, idl.Opt(idl.Nat64), idl.Nat32], [ResultCreditsPending], ["query"]),
    list_databases: idl.Func([], [ResultDatabases], ["query"]),
    list_database_members: idl.Func([idl.Text], [ResultMembers], ["query"]),
    memory_manifest: idl.Func([], [MemoryManifest], ["query"]),
    mkdir_node: idl.Func([MkdirNodeRequest], [ResultMkdirNode], []),
    move_node: idl.Func([MoveNodeRequest], [ResultMoveNode], []),
    query_context: idl.Func([QueryContextRequest], [ResultQueryContext], ["query"]),
    read_node: idl.Func([idl.Text, idl.Text], [ResultNode], ["query"]),
    read_node_context: idl.Func([NodeContextRequest], [ResultNodeContext], ["query"]),
    list_children: idl.Func([ListChildrenRequest], [ResultChildren], ["query"]),
    outgoing_links: idl.Func([OutgoingLinksRequest], [ResultLinks], ["query"]),
    preview_database_credit_purchase: idl.Func([idl.Text, idl.Nat64], [ResultUnit], ["query"]),
    repair_database_credit_purchase_cancel: idl.Func([idl.Text, idl.Nat64], [ResultUnit], []),
    repair_database_credit_purchase_complete: idl.Func([idl.Text, idl.Nat64, idl.Nat64], [ResultCreditsPurchase], []),
    revoke_database_access: idl.Func([idl.Text, idl.Text], [ResultUnit], []),
    rename_database: idl.Func([RenameDatabaseRequest], [ResultUnit], []),
    search_node_paths: idl.Func([SearchNodePathsRequest], [ResultSearch], ["query"]),
    search_nodes: idl.Func([SearchNodesRequest], [ResultSearch], ["query"]),
    source_evidence: idl.Func([SourceEvidenceRequest], [ResultSourceEvidence], ["query"]),
    purchase_database_credits: idl.Func([idl.Text, idl.Nat64], [ResultCreditsPurchase], []),
    write_node: idl.Func([WriteNodeRequest], [ResultWriteNode], []),
    write_source_for_generation: idl.Func([WriteSourceForGenerationRequest], [ResultWriteSourceForGeneration], [])
  });
};
