/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NativeAuthRouteImport } from './routes/native-auth'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IosShareRouteImport } from './routes/ios-share'
import { Route as IosAuthCallbackRouteImport } from './routes/ios-auth-callback'
import { Route as IosRouteImport } from './routes/ios'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SkillsDatabaseIdRouteImport } from './routes/skills.$databaseId'
import { Route as PPublicIdRouteImport } from './routes/p.$publicId'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as DocsSkillsRouteImport } from './routes/docs.skills'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsCanisterApiRouteImport } from './routes/docs.canister-api'
import { Route as DbDatabaseIdRouteImport } from './routes/db.$databaseId'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as DbDatabaseIdIndexRouteImport } from './routes/db.$databaseId.index'
import { Route as MarketplaceSellerPrincipalRouteImport } from './routes/marketplace.seller.$principal'
import { Route as DocsSkillsSlugRouteImport } from './routes/docs.skills.$slug'
import { Route as DbDatabaseIdTwitterImageRouteImport } from './routes/db.$databaseId.twitter-image'
import { Route as DbDatabaseIdOpengraphImageRouteImport } from './routes/db.$databaseId.opengraph-image'
import { Route as DbDatabaseIdSplatRouteImport } from './routes/db.$databaseId.$'
import { Route as DashboardProjectDatabaseIdRouteImport } from './routes/dashboard.project.$databaseId'
import { Route as ApiSourceRunRouteImport } from './routes/api.source.run'
import { Route as ApiSourceCaptureTriggerRouteImport } from './routes/api.source-capture.trigger'
import { Route as ApiQueryAnswerRouteImport } from './routes/api.query.answer'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeAuthRoute = NativeAuthRouteImport.update({
  id: '/native-auth',
  path: '/native-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IosShareRoute = IosShareRouteImport.update({
  id: '/ios-share',
  path: '/ios-share',
  getParentRoute: () => rootRouteImport,
} as any)
const IosAuthCallbackRoute = IosAuthCallbackRouteImport.update({
  id: '/ios-auth-callback',
  path: '/ios-auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IosRoute = IosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SkillsDatabaseIdRoute = SkillsDatabaseIdRouteImport.update({
  id: '/skills/$databaseId',
  path: '/skills/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PPublicIdRoute = PPublicIdRouteImport.update({
  id: '/p/$publicId',
  path: '/p/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCanisterApiRoute = DocsCanisterApiRouteImport.update({
  id: '/canister-api',
  path: '/canister-api',
  getParentRoute: () => DocsRoute,
} as any)
const DbDatabaseIdRoute = DbDatabaseIdRouteImport.update({
  id: '/db/$databaseId',
  path: '/db/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DbDatabaseIdIndexRoute = DbDatabaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DbDatabaseIdRoute,
} as any)
const MarketplaceSellerPrincipalRoute =
  MarketplaceSellerPrincipalRouteImport.update({
    id: '/seller/$principal',
    path: '/seller/$principal',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const DocsSkillsSlugRoute = DocsSkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsSkillsRoute,
} as any)
const DbDatabaseIdTwitterImageRoute =
  DbDatabaseIdTwitterImageRouteImport.update({
    id: '/twitter-image',
    path: '/twitter-image',
    getParentRoute: () => DbDatabaseIdRoute,
  } as any)
const DbDatabaseIdOpengraphImageRoute =
  DbDatabaseIdOpengraphImageRouteImport.update({
    id: '/opengraph-image',
    path: '/opengraph-image',
    getParentRoute: () => DbDatabaseIdRoute,
  } as any)
const DbDatabaseIdSplatRoute = DbDatabaseIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DbDatabaseIdRoute,
} as any)
const DashboardProjectDatabaseIdRoute =
  DashboardProjectDatabaseIdRouteImport.update({
    id: '/project/$databaseId',
    path: '/project/$databaseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiSourceRunRoute = ApiSourceRunRouteImport.update({
  id: '/api/source/run',
  path: '/api/source/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceCaptureTriggerRoute = ApiSourceCaptureTriggerRouteImport.update({
  id: '/api/source-capture/trigger',
  path: '/api/source-capture/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryAnswerRoute = ApiQueryAnswerRouteImport.update({
  id: '/api/query/answer',
  path: '/api/query/answer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cycles': typeof CyclesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/ios': typeof IosRoute
  '/ios-auth-callback': typeof IosAuthCallbackRoute
  '/ios-share': typeof IosShareRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/native-auth': typeof NativeAuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/db/$databaseId': typeof DbDatabaseIdRouteWithChildren
  '/docs/canister-api': typeof DocsCanisterApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/query/answer': typeof ApiQueryAnswerRoute
  '/api/source-capture/trigger': typeof ApiSourceCaptureTriggerRoute
  '/api/source/run': typeof ApiSourceRunRoute
  '/dashboard/project/$databaseId': typeof DashboardProjectDatabaseIdRoute
  '/db/$databaseId/$': typeof DbDatabaseIdSplatRoute
  '/db/$databaseId/opengraph-image': typeof DbDatabaseIdOpengraphImageRoute
  '/db/$databaseId/twitter-image': typeof DbDatabaseIdTwitterImageRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/marketplace/seller/$principal': typeof MarketplaceSellerPrincipalRoute
  '/db/$databaseId/': typeof DbDatabaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cycles': typeof CyclesRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/ios': typeof IosRoute
  '/ios-auth-callback': typeof IosAuthCallbackRoute
  '/ios-share': typeof IosShareRoute
  '/metrics': typeof MetricsRoute
  '/native-auth': typeof NativeAuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/docs/canister-api': typeof DocsCanisterApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/query/answer': typeof ApiQueryAnswerRoute
  '/api/source-capture/trigger': typeof ApiSourceCaptureTriggerRoute
  '/api/source/run': typeof ApiSourceRunRoute
  '/dashboard/project/$databaseId': typeof DashboardProjectDatabaseIdRoute
  '/db/$databaseId/$': typeof DbDatabaseIdSplatRoute
  '/db/$databaseId/opengraph-image': typeof DbDatabaseIdOpengraphImageRoute
  '/db/$databaseId/twitter-image': typeof DbDatabaseIdTwitterImageRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/marketplace/seller/$principal': typeof MarketplaceSellerPrincipalRoute
  '/db/$databaseId': typeof DbDatabaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cycles': typeof CyclesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/ios': typeof IosRoute
  '/ios-auth-callback': typeof IosAuthCallbackRoute
  '/ios-share': typeof IosShareRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/native-auth': typeof NativeAuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/db/$databaseId': typeof DbDatabaseIdRouteWithChildren
  '/docs/canister-api': typeof DocsCanisterApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/skills/$databaseId': typeof SkillsDatabaseIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/query/answer': typeof ApiQueryAnswerRoute
  '/api/source-capture/trigger': typeof ApiSourceCaptureTriggerRoute
  '/api/source/run': typeof ApiSourceRunRoute
  '/dashboard/project/$databaseId': typeof DashboardProjectDatabaseIdRoute
  '/db/$databaseId/$': typeof DbDatabaseIdSplatRoute
  '/db/$databaseId/opengraph-image': typeof DbDatabaseIdOpengraphImageRoute
  '/db/$databaseId/twitter-image': typeof DbDatabaseIdTwitterImageRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/marketplace/seller/$principal': typeof MarketplaceSellerPrincipalRoute
  '/db/$databaseId/': typeof DbDatabaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cycles'
    | '/dashboard'
    | '/docs'
    | '/favicon.ico'
    | '/ios'
    | '/ios-auth-callback'
    | '/ios-share'
    | '/marketplace'
    | '/metrics'
    | '/native-auth'
    | '/privacy-policy'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/.well-known/apple-app-site-association'
    | '/db/$databaseId'
    | '/docs/canister-api'
    | '/docs/cli'
    | '/docs/skills'
    | '/marketplace/$listingId'
    | '/p/$publicId'
    | '/skills/$databaseId'
    | '/dashboard/'
    | '/docs/'
    | '/marketplace/'
    | '/api/query/answer'
    | '/api/source-capture/trigger'
    | '/api/source/run'
    | '/dashboard/project/$databaseId'
    | '/db/$databaseId/$'
    | '/db/$databaseId/opengraph-image'
    | '/db/$databaseId/twitter-image'
    | '/docs/skills/$slug'
    | '/marketplace/seller/$principal'
    | '/db/$databaseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cycles'
    | '/favicon.ico'
    | '/ios'
    | '/ios-auth-callback'
    | '/ios-share'
    | '/metrics'
    | '/native-auth'
    | '/privacy-policy'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/.well-known/apple-app-site-association'
    | '/docs/canister-api'
    | '/docs/cli'
    | '/docs/skills'
    | '/marketplace/$listingId'
    | '/p/$publicId'
    | '/skills/$databaseId'
    | '/dashboard'
    | '/docs'
    | '/marketplace'
    | '/api/query/answer'
    | '/api/source-capture/trigger'
    | '/api/source/run'
    | '/dashboard/project/$databaseId'
    | '/db/$databaseId/$'
    | '/db/$databaseId/opengraph-image'
    | '/db/$databaseId/twitter-image'
    | '/docs/skills/$slug'
    | '/marketplace/seller/$principal'
    | '/db/$databaseId'
  id:
    | '__root__'
    | '/'
    | '/cycles'
    | '/dashboard'
    | '/docs'
    | '/favicon.ico'
    | '/ios'
    | '/ios-auth-callback'
    | '/ios-share'
    | '/marketplace'
    | '/metrics'
    | '/native-auth'
    | '/privacy-policy'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/.well-known/apple-app-site-association'
    | '/db/$databaseId'
    | '/docs/canister-api'
    | '/docs/cli'
    | '/docs/skills'
    | '/marketplace/$listingId'
    | '/p/$publicId'
    | '/skills/$databaseId'
    | '/dashboard/'
    | '/docs/'
    | '/marketplace/'
    | '/api/query/answer'
    | '/api/source-capture/trigger'
    | '/api/source/run'
    | '/dashboard/project/$databaseId'
    | '/db/$databaseId/$'
    | '/db/$databaseId/opengraph-image'
    | '/db/$databaseId/twitter-image'
    | '/docs/skills/$slug'
    | '/marketplace/seller/$principal'
    | '/db/$databaseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyclesRoute: typeof CyclesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  IosRoute: typeof IosRoute
  IosAuthCallbackRoute: typeof IosAuthCallbackRoute
  IosShareRoute: typeof IosShareRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MetricsRoute: typeof MetricsRoute
  NativeAuthRoute: typeof NativeAuthRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DbDatabaseIdRoute: typeof DbDatabaseIdRouteWithChildren
  PPublicIdRoute: typeof PPublicIdRoute
  SkillsDatabaseIdRoute: typeof SkillsDatabaseIdRoute
  ApiQueryAnswerRoute: typeof ApiQueryAnswerRoute
  ApiSourceCaptureTriggerRoute: typeof ApiSourceCaptureTriggerRoute
  ApiSourceRunRoute: typeof ApiSourceRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-auth': {
      id: '/native-auth'
      path: '/native-auth'
      fullPath: '/native-auth'
      preLoaderRoute: typeof NativeAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios-share': {
      id: '/ios-share'
      path: '/ios-share'
      fullPath: '/ios-share'
      preLoaderRoute: typeof IosShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios-auth-callback': {
      id: '/ios-auth-callback'
      path: '/ios-auth-callback'
      fullPath: '/ios-auth-callback'
      preLoaderRoute: typeof IosAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios': {
      id: '/ios'
      path: '/ios'
      fullPath: '/ios'
      preLoaderRoute: typeof IosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/skills/$databaseId': {
      id: '/skills/$databaseId'
      path: '/skills/$databaseId'
      fullPath: '/skills/$databaseId'
      preLoaderRoute: typeof SkillsDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$publicId': {
      id: '/p/$publicId'
      path: '/p/$publicId'
      fullPath: '/p/$publicId'
      preLoaderRoute: typeof PPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/canister-api': {
      id: '/docs/canister-api'
      path: '/canister-api'
      fullPath: '/docs/canister-api'
      preLoaderRoute: typeof DocsCanisterApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/db/$databaseId': {
      id: '/db/$databaseId'
      path: '/db/$databaseId'
      fullPath: '/db/$databaseId'
      preLoaderRoute: typeof DbDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$databaseId/': {
      id: '/db/$databaseId/'
      path: '/'
      fullPath: '/db/$databaseId/'
      preLoaderRoute: typeof DbDatabaseIdIndexRouteImport
      parentRoute: typeof DbDatabaseIdRoute
    }
    '/marketplace/seller/$principal': {
      id: '/marketplace/seller/$principal'
      path: '/seller/$principal'
      fullPath: '/marketplace/seller/$principal'
      preLoaderRoute: typeof MarketplaceSellerPrincipalRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/skills/$slug': {
      id: '/docs/skills/$slug'
      path: '/$slug'
      fullPath: '/docs/skills/$slug'
      preLoaderRoute: typeof DocsSkillsSlugRouteImport
      parentRoute: typeof DocsSkillsRoute
    }
    '/db/$databaseId/twitter-image': {
      id: '/db/$databaseId/twitter-image'
      path: '/twitter-image'
      fullPath: '/db/$databaseId/twitter-image'
      preLoaderRoute: typeof DbDatabaseIdTwitterImageRouteImport
      parentRoute: typeof DbDatabaseIdRoute
    }
    '/db/$databaseId/opengraph-image': {
      id: '/db/$databaseId/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/db/$databaseId/opengraph-image'
      preLoaderRoute: typeof DbDatabaseIdOpengraphImageRouteImport
      parentRoute: typeof DbDatabaseIdRoute
    }
    '/db/$databaseId/$': {
      id: '/db/$databaseId/$'
      path: '/$'
      fullPath: '/db/$databaseId/$'
      preLoaderRoute: typeof DbDatabaseIdSplatRouteImport
      parentRoute: typeof DbDatabaseIdRoute
    }
    '/dashboard/project/$databaseId': {
      id: '/dashboard/project/$databaseId'
      path: '/project/$databaseId'
      fullPath: '/dashboard/project/$databaseId'
      preLoaderRoute: typeof DashboardProjectDatabaseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/source/run': {
      id: '/api/source/run'
      path: '/api/source/run'
      fullPath: '/api/source/run'
      preLoaderRoute: typeof ApiSourceRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source-capture/trigger': {
      id: '/api/source-capture/trigger'
      path: '/api/source-capture/trigger'
      fullPath: '/api/source-capture/trigger'
      preLoaderRoute: typeof ApiSourceCaptureTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query/answer': {
      id: '/api/query/answer'
      path: '/api/query/answer'
      fullPath: '/api/query/answer'
      preLoaderRoute: typeof ApiQueryAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectDatabaseIdRoute: typeof DashboardProjectDatabaseIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectDatabaseIdRoute: DashboardProjectDatabaseIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsSkillsRouteChildren {
  DocsSkillsSlugRoute: typeof DocsSkillsSlugRoute
}

const DocsSkillsRouteChildren: DocsSkillsRouteChildren = {
  DocsSkillsSlugRoute: DocsSkillsSlugRoute,
}

const DocsSkillsRouteWithChildren = DocsSkillsRoute._addFileChildren(
  DocsSkillsRouteChildren,
)

interface DocsRouteChildren {
  DocsCanisterApiRoute: typeof DocsCanisterApiRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsSkillsRoute: typeof DocsSkillsRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCanisterApiRoute: DocsCanisterApiRoute,
  DocsCliRoute: DocsCliRoute,
  DocsSkillsRoute: DocsSkillsRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceSellerPrincipalRoute: typeof MarketplaceSellerPrincipalRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceSellerPrincipalRoute: MarketplaceSellerPrincipalRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface DbDatabaseIdRouteChildren {
  DbDatabaseIdSplatRoute: typeof DbDatabaseIdSplatRoute
  DbDatabaseIdOpengraphImageRoute: typeof DbDatabaseIdOpengraphImageRoute
  DbDatabaseIdTwitterImageRoute: typeof DbDatabaseIdTwitterImageRoute
  DbDatabaseIdIndexRoute: typeof DbDatabaseIdIndexRoute
}

const DbDatabaseIdRouteChildren: DbDatabaseIdRouteChildren = {
  DbDatabaseIdSplatRoute: DbDatabaseIdSplatRoute,
  DbDatabaseIdOpengraphImageRoute: DbDatabaseIdOpengraphImageRoute,
  DbDatabaseIdTwitterImageRoute: DbDatabaseIdTwitterImageRoute,
  DbDatabaseIdIndexRoute: DbDatabaseIdIndexRoute,
}

const DbDatabaseIdRouteWithChildren = DbDatabaseIdRoute._addFileChildren(
  DbDatabaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyclesRoute: CyclesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  FaviconDoticoRoute: FaviconDoticoRoute,
  IosRoute: IosRoute,
  IosAuthCallbackRoute: IosAuthCallbackRoute,
  IosShareRoute: IosShareRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MetricsRoute: MetricsRoute,
  NativeAuthRoute: NativeAuthRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DbDatabaseIdRoute: DbDatabaseIdRouteWithChildren,
  PPublicIdRoute: PPublicIdRoute,
  SkillsDatabaseIdRoute: SkillsDatabaseIdRoute,
  ApiQueryAnswerRoute: ApiQueryAnswerRoute,
  ApiSourceCaptureTriggerRoute: ApiSourceCaptureTriggerRoute,
  ApiSourceRunRoute: ApiSourceRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
