/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AssistantEnv` (hash: 64c3cf1908e5b6d523f330916dcaae34)
interface __BaseEnv_AssistantEnv {
	ASSISTANT_DB: D1Database;
	ASSISTANT_ENABLED: string;
	ASSISTANT_NATIVE_ENABLED: string;
	ASSISTANT_WEB_ENABLED: string;
	ASSISTANT_INVITED_PRINCIPALS: string;
	ASSISTANT_LIMITS: string;
	KINIC_WIKI_CANISTER_ID: string;
	ASSISTANT_ORIGIN: string;
	ASSISTANT_DERIVATION_ORIGIN: string;
	AUTH_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		ASSISTANT_DB: D1Database;
		ASSISTANT_ENABLED: string;
		ASSISTANT_NATIVE_ENABLED: string;
		ASSISTANT_WEB_ENABLED: string;
		ASSISTANT_INVITED_PRINCIPALS: string;
		ASSISTANT_LIMITS: string;
		KINIC_WIKI_CANISTER_ID: string;
		ASSISTANT_ORIGIN: string;
		ASSISTANT_DERIVATION_ORIGIN: string;
		AUTH_RATE_LIMIT: RateLimit;
	}
	interface Env extends __BaseEnv_AssistantEnv {}
}
interface AssistantEnv extends __BaseEnv_AssistantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSISTANT_ENABLED" | "ASSISTANT_NATIVE_ENABLED" | "ASSISTANT_WEB_ENABLED" | "ASSISTANT_INVITED_PRINCIPALS" | "ASSISTANT_LIMITS" | "KINIC_WIKI_CANISTER_ID" | "ASSISTANT_ORIGIN" | "ASSISTANT_DERIVATION_ORIGIN">> {}
}
