/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AssistantEnv` (hash: 7f905c7b30291931ff30101174ff8e5f)
interface __BaseEnv_AssistantEnv {
	ASSISTANT_ENABLED: string;
	ASSISTANT_INVITED_PRINCIPALS: string;
	ASSISTANT_LIMITS: string;
	KINIC_WIKI_CANISTER_ID: string;
	ASSISTANT_ORIGIN: string;
	ASSISTANT_DERIVATION_ORIGIN: string;
	ASSISTANT_AUTH: DurableObjectNamespace<import("./src/index").AssistantAuth>;
	ASSISTANT_USERS: DurableObjectNamespace<import("./src/index").AssistantUser>;
	AUTH_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AssistantAuth" | "AssistantUser";
	}
	interface StagingEnv {
		ASSISTANT_ENABLED: string;
		ASSISTANT_INVITED_PRINCIPALS: string;
		ASSISTANT_LIMITS: string;
		KINIC_WIKI_CANISTER_ID: string;
		ASSISTANT_ORIGIN: string;
		ASSISTANT_DERIVATION_ORIGIN: string;
		ASSISTANT_AUTH: DurableObjectNamespace<import("./src/index").AssistantAuth>;
		ASSISTANT_USERS: DurableObjectNamespace<import("./src/index").AssistantUser>;
		AUTH_RATE_LIMIT: RateLimit;
	}
	interface Env extends __BaseEnv_AssistantEnv {}
}
interface AssistantEnv extends __BaseEnv_AssistantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSISTANT_ENABLED" | "ASSISTANT_INVITED_PRINCIPALS" | "ASSISTANT_LIMITS" | "KINIC_WIKI_CANISTER_ID" | "ASSISTANT_ORIGIN" | "ASSISTANT_DERIVATION_ORIGIN">> {}
}
