/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AssistantEnv` (hash: d42a3393ae743b79281af1b7e45cc9dd)
interface __BaseEnv_AssistantEnv {
	ASSISTANT_DB: D1Database;
	ASSISTANT_ENABLED: string;
	KINIC_WIKI_CANISTER_ID: string;
	ASSISTANT_ORIGIN: string;
	ASSISTANT_DERIVATION_ORIGIN: string;
	AUTH_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		ASSISTANT_DB: D1Database;
		ASSISTANT_ENABLED: string;
		KINIC_WIKI_CANISTER_ID: string;
		ASSISTANT_ORIGIN: string;
		ASSISTANT_DERIVATION_ORIGIN: string;
		AUTH_RATE_LIMIT: RateLimit;
	}
	interface Env extends __BaseEnv_AssistantEnv {}
}
interface AssistantEnv extends __BaseEnv_AssistantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSISTANT_ENABLED" | "KINIC_WIKI_CANISTER_ID" | "ASSISTANT_ORIGIN" | "ASSISTANT_DERIVATION_ORIGIN">> {}
}
